"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
[](bg:kanagawa_yellow fg:kanagawa_orange)\
$directory\
[](fg:kanagawa_yellow bg:kanagawa_aqua)\
$git_branch\
$git_status\
[](fg:kanagawa_aqua bg:kanagawa_blue)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:kanagawa_blue bg:kanagawa_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:kanagawa_bg3 bg:kanagawa_bg1)\
$time\
$line_break$character"""

palette = 'kanagawa'

[palettes.kanagawa]
kanagawa_fg = '#dcd7ba'
kanagawa_bg0 = '#223249'
kanagawa_bg1 = '#729f94'
kanagawa_bg2 = '#658594'
kanagawa_bg3 = '#54546D'
kanagawa_gray = '#727169'
kanagawa_red = '#c34043'
kanagawa_green = '#76946a'
kanagawa_yellow = '#836f4a'
kanagawa_blue = '#2d4f67'
kanagawa_purple = '#766b90'
kanagawa_aqua = '#597b75'
kanagawa_orange = '#af478F'
kanagawa_bright_red = '#e46876'
kanagawa_bright_green = '#98bb6c'
kanagawa_bright_yellow = '#c0a36e'
kanagawa_bright_blue = '#7fb4ca'
kanagawa_bright_purple = '#957fb8'
kanagawa_bright_aqua = '#8ea4a2'
kanagawa_bright_orange = '#dca561'

[os]
disabled = false
style = "bg:kanagawa_orange fg:kanagawa_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:kanagawa_orange fg:kanagawa_fg"
style_root = "bg:kanagawa_orange fg:kanagawa_fg"
format = '[ $user ]($style)'

[directory]
style = "fg:kanagawa_fg bg:kanagawa_yellow"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:kanagawa_aqua"
format = '[[ $symbol $branch ](fg:kanagawa_fg bg:kanagawa_aqua)]($style)'

[git_status]
style = "bg:kanagawa_aqua"
format = '[[($all_status$ahead_behind )](fg:kanagawa_fg bg:kanagawa_aqua)]($style)'

[nodejs]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[c]
symbol = " "
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[cpp]
symbol = " "
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[rust]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[golang]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[php]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[java]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[haskell]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[python]
symbol = ""
style = "bg:kanagawa_blue"
format = '[[ $symbol( $version) ](fg:kanagawa_fg bg:kanagawa_blue)]($style)'

[docker_context]
symbol = ""
style = "bg:kanagawa_bg3"
format = '[[ $symbol( $context) ](fg:kanagawa_bright_blue bg:kanagawa_bg3)]($style)'

[conda]
style = "bg:kanagawa_bg3"
format = '[[ $symbol( $environment) ](fg:kanagawa_bright_blue bg:kanagawa_bg3)]($style)'

[pixi]
style = "bg:kanagawa_bg3"
format = '[[ $symbol( $version)( $environment) ](fg:kanagawa_fg bg:kanagawa_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:kanagawa_bg1"
format = '[[  $time ](fg:kanagawa_fg bg:kanagawa_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:kanagawa_green)'
error_symbol = '[](bold fg:kanagawa_red)'
vimcmd_symbol = '[](bold fg:kanagawa_green)'
vimcmd_replace_one_symbol = '[](bold fg:kanagawa_purple)'
vimcmd_replace_symbol = '[](bold fg:kanagawa_purple)'
vimcmd_visual_symbol = '[](bold fg:kanagawa_yellow)'
